version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: pm-internship-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: pm-internship
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./backend/scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - pm-internship-network

  # Redis Cache
  redis:
    image: redis:7.2-alpine
    container_name: pm-internship-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - pm-internship-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pm-internship-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3000
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/pm-internship?authSource=admin
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      GOOGLE_CLOUD_PROJECT_ID: pm-internship-bot
      ETHEREUM_RPC_URL: https://mainnet.infura.io/v3/your-infura-key
      FRONTEND_URL: http://localhost:5173
    ports:
      - "3000:3000"
    volumes:
      - ./backend/models:/app/models
      - ./backend/uploads:/app/uploads
    depends_on:
      - mongodb
      - redis
    networks:
      - pm-internship-network

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pm-internship-frontend
    restart: unless-stopped
    environment:
      VITE_API_URL: http://localhost:3000/api
      VITE_SOCKET_URL: http://localhost:3000
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - pm-internship-network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: pm-internship-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
    networks:
      - pm-internship-network

volumes:
  mongodb_data:
  redis_data:

networks:
  pm-internship-network:
    driver: bridge